services:
  overseerr:
    user: "1002:281"
    image: ghcr.io/linuxserver/overseerr:1.33.2
    container_name: overseerr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/overseerr:/config

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`requests.theblaskies.com`)
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.tls.certresolver=cloudflare
      - traefik.http.services.overseerr.loadbalancer.server.port=5055

networks:
  media_net:
    user: "1002:281"
    external: true
  proxy_net:
    user: "1002:281"
    external: true
