services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:f6a782e44742a02bdb6032d32ebb4e9615e261140f879be897b28cdb40ff800e
    container_name: overseerr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/overseerr:/config

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`requests.theblaskies.com`)
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.tls.certresolver=cloudflare
      - traefik.http.services.overseerr.loadbalancer.server.port=5055

networks:
  media_net:
    external: true
  proxy_net:
    external: true
