services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.17.2
    container_name: prowlarr
    restart: unless-stopped
    user: "1002:281"

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/prowlarr:/config

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.theblaskies.com`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=cloudflare
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    restart: unless-stopped
    user: "1002:281"

    environment:
      LOG_LEVEL: info
      LOG_HTML: "false"
      CAPTCHA_SOLVER: none

    networks:
      - media_net

networks:
  media_net:
    external: true
  proxy_net:
    external: true
