services:
  radarr:
    image: ghcr.io/linuxserver/radarr:6.0.4@sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c
    container_name: radarr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/data:/data
      - /mnt/user/data/recycle-bin:/data/recycle-bin
    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.theblaskies.com`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      - traefik.http.services.radarr.loadbalancer.server.port=7878

networks:
  media_net:
    external: true
  proxy_net:
    external: true
