services:
  kometa:
    image: kometateam/kometa:latest@sha256:7c646da49169eacc3a1e5462af86de2b4176b7a68673cf7996709f431c5fdc7d
    container_name: kometa
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/kometa:/config
      - /mnt/user/data/media/assets:/config/assets:rw

    networks:
      - media_net
      - proxy_net

networks:
  media_net:
    external: true

  proxy_net:
    external: true
