services:
  cloudflared:
    image: cloudflare/cloudflared@sha256:89ee50efb1e9cb2ae30281a8a404fed95eb8f02f0a972617526f8c5b417acae2
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
