services:
  cloudflared:
    image: cloudflare/cloudflared@sha256:e9bcb2ef08d25632ff74344e73a025f4f4bf12718335b196fa0e670cacace8c5
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
