http:
  routers:
    logout:
      rule: Host(`theblaskies.com`) && Path(`/logout`)
      entryPoints:
        - websecure
      service: oauth2-proxy
      middlewares:
        - oauth2-logout
      tls:
        certResolver: cloudflare

  middlewares:
    oauth2-logout:
      redirectRegex:
        regex: ^/logout$
        replacement: /oauth2/sign_out?rd=https://home.theblaskies.com
        permanent: false
