http:
  routers:
    unraid:
      rule: Host(`unraid.theblaskies.com`)
      entryPoints:
        - websecure
      service: unraid
      tls:
        certResolver: cloudflare

  services:
    unraid:
      loadBalancer:
        servers:
          - url: https://10-69-1-100.674cc815393e093c04914555634a26ce43160a3a.myunraid.net:19443
        passHostHeader: true
