services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest@sha256:20a5656c4af4854e1877046294f77113f949d27e35940a9a65f231423d063207
    container_name: tdarr
    restart: unless-stopped

    env_file:
      - .env

    environment:
      serverIP: ${TDARR_SERVER_IP}
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_WEBUI_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/data/media:/media
      - /mnt/cache/temp/tdarr-temp:/temp

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.theblaskies.com`)
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.tls.certresolver=cloudflare
      - traefik.http.services.tdarr.loadbalancer.server.port=8265

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest@sha256:62e14509bc19dea9b6f5dc85d0942163b6fa240d780a53eb590d894d46c9e1f2
    container_name: tdarr-node
    restart: unless-stopped

    env_file:
      - .env

    environment:
      nodeName: ${TDARR_NODE_NAME}
      serverIP: tdarr
      serverPort: ${TDARR_SERVER_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/node:/app/configs
      - /mnt/user/data/media:/media
      - /mnt/cache/temp/tdarr-temp:/temp

    runtime: nvidia

    networks:
      - media_net

networks:
  media_net:
    external: true
  proxy_net:
    external: true
