services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    user: "99:100"

    env_file:
      - .env

    environment:
      serverIP: ${TDARR_SERVER_IP}
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_WEBUI_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/data/media:/media
      - /tmp:/temp

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.theblaskies.com`)
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.tls.certresolver=cloudflare
      - traefik.http.services.tdarr.loadbalancer.server.port=8265

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    user: "99:100"

    env_file:
      - .env

    environment:
      nodeName: ${TDARR_NODE_NAME}
      serverIP: tdarr
      serverPort: ${TDARR_SERVER_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/node:/app/configs
      - /mnt/user/data/media:/media
      - /tmp:/temp

    runtime: nvidia

    networks:
      - media_net

networks:
  media_net:
    external: true
  proxy_net:
    external: true
