services:
  docker-socket-proxy:
    user: "1002:281"
    image: ghcr.io/tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    restart: unless-stopped

    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      TASKS: 1
      EVENTS: 1
      INFO: 1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - proxy_net


  traefik:
    user: "1002:281"
    image: traefik@sha256:16acb89c6db341182970d6fdafece31303b0a380a8ed7aa51682e225229bf1d2
    container_name: traefik
    restart: unless-stopped

    env_file:
      - .env

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "443:443"

    volumes:
      # Static config
      - /mnt/user/appdata/komodo/repos/Blaskielab/stacks/infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro

      # Dynamic config (Git-managed)
      - /mnt/user/appdata/komodo/repos/Blaskielab/stacks/infra/traefik/dynamic:/etc/traefik/dynamic:ro

      # ACME storage
      - /mnt/user/appdata/traefik/acme:/etc/traefik/acme

    networks:
      - proxy_net

networks:
  proxy_net:
    user: "1002:281"
    external: true
