############################
# ðŸ¦Ž KOMODO CORE CONFIG
# Blaskielab â€“ scaffolded
############################

# Cosmetic
title = "Blaskielab Komodo"

############################
# AUTH / LOGIN
############################

# Disable local auth (we plan to use OIDC)
local_auth = true
init_admin_username = "admin"
init_admin_password = "Barnacle15"

# Prevent open registration
disable_user_registration = true
enable_new_users = false

############################
# OIDC (SCAFFOLD ONLY)
############################

oidc_enabled = true

# Example (PocketID / Authentik later)
oidc_provider = "https://id.theblaskies.com"
oidc_redirect_host = "https://komodo.theblaskies.com"

oidc_client_id = "3882d5c1-5602-48ed-bbce-2b7aed50808b"
oidc_client_secret = "IjTvqRCRMah7D105zuSXXKfahiS6Xh9I"
oidc_use_full_email = false
oidc_additional_audiences = []


disable_confirm_dialog = true
