services:
  plex:
    image: ghcr.io/linuxserver/plex:latest@sha256:b19a5e34c6f8dd42abf88556b8aa5c8987c0c34820aaeaa320a02d8c17fdaab3
    container_name: plex
    restart: unless-stopped
    runtime: nvidia

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/data/media:/media
    tmpfs:
      - /transcode:size=16G

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.theblaskies.com`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400

networks:
  media_net:
    external: true
  proxy_net:
    external: true
