services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.4@sha256:7d0a091a63889ce1e4ac4c90595ebd2c50ba5a5df7039a4f4d2be6c2aed6d4ae
    container_name: bazarr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/data/media:/media

    networks:
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.theblaskies.com`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=cloudflare
      - traefik.http.services.bazarr.loadbalancer.server.port=6767

networks:
  proxy_net:
    external: true
