services:
  unpackerr:
    image: ghcr.io/unpackerr/unpackerr:0.13.1@sha256:04fcb43fa70e6db88331962760607842cdf19889e6d35d9d2fde0cf6a1550eaf
    container_name: unpackerr
    restart: unless-stopped
    user: "1002:281"

    env_file:
      - .env

    volumes:
      - /mnt/user/data:/data

    networks:
      - media_net
networks:
   media_net:
     external: true
