services:
  unpackerr:
    image: ghcr.io/unpackerr/unpackerr:0.14.5@sha256:dc72256942ce50d1c8a1aeb5aa85b6ae2680a36eefd2182129d8d210fce78044
    container_name: unpackerr
    restart: unless-stopped
    user: "1002:281"

    env_file:
      - .env

    volumes:
      - /mnt/user/data:/data

    networks:
      - media_net
networks:
   media_net:
     external: true
