services:
  apprise:
    image: caronc/apprise-api:latest@sha256:5057fef2a2f4011c3c955a773cc4c008c647ec3619d009b3b3db8e5c864df9d7
    container_name: apprise
    restart: unless-stopped

    # Unraid-native permissions
    user: "99:100"

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/apprise/config:/config

    networks:
      - infra_net

    # Internal-only service
    # Exposed only to ntfy and other containers

networks:
  infra_net:
    external: true
