services:
  apprise:
    image: caronc/apprise-api:latest@sha256:1df7597f3f862034211be7a70b7fb683331967e00556f7ea9cbaba051c736bf3
    container_name: apprise
    restart: unless-stopped

    # Unraid-native permissions
    user: "99:100"

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/apprise/config:/config

    networks:
      - infra_net

    # Internal-only service
    # Exposed only to ntfy and other containers

networks:
  infra_net:
    external: true
